name: Hello World

on:
  workflow_dispatch:

jobs:
  test-hello-world:
    runs-on: node:slim
    steps:
      # install
      - name: install
      - run: npm install typescript @types/google-apps-script
      - run: npm install  jest  ts-node ts-jest @types/jest
      # test
      - name: test
      - run: npx jest
